import type { ProviderListing } from '../types';

export const MOCK_LISTINGS: Record<string, ProviderListing[]> = {
  amazon: [
    {
      merchantProductId: 'AMZ-IPH17-256-BLK',
      title: 'Apple iPhone 17 256GB Black',
      brand: 'Apple',
      model: 'iPhone 17',
      category: 'smartphones',
      subcategory: 'mobile',
      price: 84900,
      mrp: 89900,
      currency: 'INR',
      availability: 'In Stock',
      seller: 'Amazon',
      sellerRating: 4.5,
      warranty: '1 Year Manufacturer Warranty',
      returnPolicy: '10 days replacement',
      deliveryInfo: 'Free delivery by tomorrow',
      rating: 4.6,
      reviewCount: 1240,
      url: 'https://www.amazon.in/dp/AMZ-IPH17-256-BLK',
      imageUrl: '/products/iphone17.jpg',
      specifications: { storage: '256GB', color: 'Black', ram: '8GB' },
      identifiers: { model: 'A3101', gtin: '0194253801234' },
      dataFreshness: 'LIVE',
      sourceTimestamp: new Date(),
    },
    {
      merchantProductId: 'AMZ-SAM-TV55-4K',
      title: 'Samsung 55 Inch 4K Smart TV XYZ Series',
      brand: 'Samsung',
      model: 'XYZ55',
      category: 'electronics',
      subcategory: 'television',
      price: 56490,
      mrp: 74999,
      currency: 'INR',
      availability: 'In Stock',
      seller: 'Amazon',
      sellerRating: 4.4,
      warranty: '1 Year Warranty + 1 Year Extended',
      returnPolicy: '7 days replacement',
      deliveryInfo: 'Free delivery in 3 days',
      rating: 4.3,
      reviewCount: 890,
      url: 'https://www.amazon.in/dp/AMZ-SAM-TV55-4K',
      imageUrl: '/products/samsung-tv.jpg',
      specifications: { screenSize: '55 inch', resolution: '4K UHD', smartTV: 'Yes' },
      identifiers: { model: 'UA55XYZ', gtin: '8806094567890' },
      dataFreshness: 'LIVE',
      sourceTimestamp: new Date(),
    },
    {
      merchantProductId: 'AMZ-LAP-GAMING-70K',
      title: 'ASUS TUF Gaming F15 Intel i5 RTX 4050 16GB RAM 512GB SSD',
      brand: 'ASUS',
      model: 'TUF F15',
      category: 'laptops',
      subcategory: 'gaming',
      price: 68990,
      mrp: 84990,
      currency: 'INR',
      availability: 'In Stock',
      seller: 'Amazon',
      sellerRating: 4.3,
      warranty: '1 Year Onsite Warranty',
      returnPolicy: '7 days replacement',
      deliveryInfo: 'Free delivery in 2 days',
      rating: 4.4,
      reviewCount: 567,
      url: 'https://www.amazon.in/dp/AMZ-LAP-GAMING-70K',
      specifications: { ram: '16GB', storage: '512GB SSD', gpu: 'RTX 4050', processor: 'Intel i5' },
      identifiers: { model: 'FX507VV-LP123' },
      dataFreshness: 'LIVE',
      sourceTimestamp: new Date(),
    },
    {
      merchantProductId: 'AMZ-IPH17-128-BLU',
      title: 'Apple iPhone 17 128GB Blue',
      brand: 'Apple',
      model: 'iPhone 17',
      category: 'smartphones',
      price: 74900,
      mrp: 79900,
      currency: 'INR',
      availability: 'In Stock',
      seller: 'Amazon',
      sellerRating: 4.5,
      warranty: '1 Year Manufacturer Warranty',
      returnPolicy: '10 days replacement',
      url: 'https://www.amazon.in/dp/AMZ-IPH17-128-BLU',
      specifications: { storage: '128GB', color: 'Blue', ram: '8GB' },
      identifiers: { model: 'A3100', gtin: '0194253801235' },
      dataFreshness: 'LIVE',
      sourceTimestamp: new Date(),
    },
    {
      merchantProductId: 'AMZ-WM-FAM4',
      title: 'LG 8kg Front Load Washing Machine FHM1208',
      brand: 'LG',
      model: 'FHM1208',
      category: 'home_appliances',
      subcategory: 'washing_machine',
      price: 32990,
      mrp: 42990,
      currency: 'INR',
      availability: 'In Stock',
      seller: 'Amazon',
      sellerRating: 4.2,
      warranty: '2 Year Comprehensive Warranty',
      returnPolicy: '10 days replacement',
      rating: 4.5,
      reviewCount: 2340,
      url: 'https://www.amazon.in/dp/AMZ-WM-FAM4',
      specifications: { capacity: '8kg', type: 'Front Load', energyRating: '5 Star' },
      identifiers: { model: 'FHM1208ZDM' },
      dataFreshness: 'LIVE',
      sourceTimestamp: new Date(),
    },
  ],
  flipkart: [
    {
      merchantProductId: 'FK-IPH17-256-BLK',
      title: 'Apple iPhone 17 (256 GB, Black)',
      brand: 'Apple',
      model: 'iPhone 17',
      category: 'smartphones',
      price: 82900,
      mrp: 89900,
      currency: 'INR',
      availability: 'In Stock',
      seller: 'Flipkart Assured',
      sellerRating: 4.6,
      warranty: '1 Year Brand Warranty',
      returnPolicy: '7 days replacement',
      deliveryInfo: 'Delivery by tomorrow',
      rating: 4.5,
      reviewCount: 2100,
      url: 'https://www.flipkart.com/apple-iphone-17-256gb-black/p/fk-iph17-256-blk',
      specifications: { storage: '256GB', color: 'Black', ram: '8GB' },
      identifiers: { model: 'A3101', gtin: '0194253801234' },
      dataFreshness: 'LIVE',
      sourceTimestamp: new Date(),
    },
    {
      merchantProductId: 'FK-SAM-TV55-4K',
      title: 'Samsung XYZ 55 UHD Smart Television',
      brand: 'Samsung',
      model: 'XYZ55',
      category: 'electronics',
      price: 54999,
      mrp: 72999,
      currency: 'INR',
      availability: 'In Stock',
      seller: 'Flipkart Assured',
      sellerRating: 4.5,
      warranty: '1 Year Standard Warranty',
      returnPolicy: '7 days replacement',
      rating: 4.4,
      reviewCount: 1560,
      url: 'https://www.flipkart.com/samsung-xyz-55-uhd-tv/p/fk-sam-tv55',
      specifications: { screenSize: '55 inch', resolution: '4K UHD', smartTV: 'Yes' },
      identifiers: { model: 'UA55XYZ', gtin: '8806094567890' },
      dataFreshness: 'LIVE',
      sourceTimestamp: new Date(),
    },
    {
      merchantProductId: 'FK-LAP-GAMING-70K',
      title: 'ASUS TUF Gaming Laptop i5 16GB 512GB RTX 4050',
      brand: 'ASUS',
      model: 'TUF F15',
      category: 'laptops',
      price: 67490,
      mrp: 82990,
      currency: 'INR',
      availability: 'In Stock',
      seller: 'Flipkart Assured',
      sellerRating: 4.4,
      warranty: '1 Year Warranty',
      returnPolicy: '7 days replacement',
      rating: 4.3,
      reviewCount: 890,
      url: 'https://www.flipkart.com/asus-tuf-gaming-f15/p/fk-lap-gaming',
      specifications: { ram: '16GB', storage: '512GB SSD', gpu: 'RTX 4050', processor: 'Intel i5' },
      identifiers: { model: 'FX507VV-LP123' },
      dataFreshness: 'LIVE',
      sourceTimestamp: new Date(),
    },
    {
      merchantProductId: 'FK-WM-FAM4',
      title: 'LG 8 Kg Fully Automatic Front Load Washing Machine',
      brand: 'LG',
      model: 'FHM1208',
      category: 'home_appliances',
      price: 31490,
      mrp: 41990,
      currency: 'INR',
      availability: 'In Stock',
      seller: 'Flipkart Assured',
      sellerRating: 4.3,
      warranty: '2 Year Warranty',
      returnPolicy: '7 days replacement',
      rating: 4.6,
      reviewCount: 3200,
      url: 'https://www.flipkart.com/lg-8kg-washing-machine/p/fk-wm-fam4',
      specifications: { capacity: '8kg', type: 'Front Load', energyRating: '5 Star' },
      identifiers: { model: 'FHM1208ZDM' },
      dataFreshness: 'LIVE',
      sourceTimestamp: new Date(),
    },
  ],
  croma: [
    {
      merchantProductId: 'CR-IPH17-256-BLK',
      title: 'Apple iPhone 17 256GB - Black',
      brand: 'Apple',
      model: 'iPhone 17',
      category: 'smartphones',
      price: 83900,
      mrp: 89900,
      currency: 'INR',
      availability: 'In Stock',
      seller: 'Croma',
      sellerRating: 4.4,
      warranty: '1 Year Apple Warranty',
      returnPolicy: '7 days return',
      deliveryInfo: 'Store pickup available',
      rating: 4.5,
      reviewCount: 450,
      url: 'https://www.croma.com/apple-iphone-17-256gb-black/p/cr-iph17',
      specifications: { storage: '256GB', color: 'Black', ram: '8GB' },
      identifiers: { model: 'A3101', gtin: '0194253801234' },
      dataFreshness: 'LIVE',
      sourceTimestamp: new Date(),
    },
    {
      merchantProductId: 'CR-SAM-TV55-4K',
      title: 'Samsung 55XYZ UHD TV',
      brand: 'Samsung',
      model: 'XYZ55',
      category: 'electronics',
      price: 58999,
      mrp: 74999,
      currency: 'INR',
      availability: 'In Stock',
      seller: 'Croma',
      sellerRating: 4.3,
      warranty: '1 Year Warranty',
      returnPolicy: '7 days return',
      rating: 4.2,
      reviewCount: 320,
      url: 'https://www.croma.com/samsung-55xyz-uhd-tv/p/cr-sam-tv55',
      specifications: { screenSize: '55 inch', resolution: '4K UHD', smartTV: 'Yes' },
      identifiers: { model: 'UA55XYZ', gtin: '8806094567890' },
      dataFreshness: 'LIVE',
      sourceTimestamp: new Date(),
    },
    {
      merchantProductId: 'CR-LAP-GAMING-70K',
      title: 'ASUS TUF F15 Gaming Laptop 16GB/512GB',
      brand: 'ASUS',
      model: 'TUF F15',
      category: 'laptops',
      price: 69990,
      mrp: 84990,
      currency: 'INR',
      availability: 'Limited Stock',
      seller: 'Croma',
      sellerRating: 4.2,
      warranty: '1 Year Warranty',
      returnPolicy: '7 days return',
      rating: 4.1,
      reviewCount: 180,
      url: 'https://www.croma.com/asus-tuf-f15-gaming/p/cr-lap-gaming',
      specifications: { ram: '16GB', storage: '512GB SSD', gpu: 'RTX 4050', processor: 'Intel i5' },
      identifiers: { model: 'FX507VV-LP123' },
      dataFreshness: 'LIVE',
      sourceTimestamp: new Date(),
    },
    {
      merchantProductId: 'CR-WM-FAM4',
      title: 'LG Front Load Washing Machine 8kg FHM1208',
      brand: 'LG',
      model: 'FHM1208',
      category: 'home_appliances',
      price: 33990,
      mrp: 42990,
      currency: 'INR',
      availability: 'In Stock',
      seller: 'Croma',
      sellerRating: 4.1,
      warranty: '2 Year Warranty',
      returnPolicy: '7 days return',
      rating: 4.4,
      reviewCount: 210,
      url: 'https://www.croma.com/lg-8kg-washing-machine/p/cr-wm-fam4',
      specifications: { capacity: '8kg', type: 'Front Load', energyRating: '5 Star' },
      identifiers: { model: 'FHM1208ZDM' },
      dataFreshness: 'LIVE',
      sourceTimestamp: new Date(),
    },
  ],
};

export const MOCK_MERCHANTS = {
  amazon: { slug: 'amazon', name: 'Amazon India', affiliateTag: 'smartbuy-21', commissionRate: 0.02 },
  flipkart: { slug: 'flipkart', name: 'Flipkart', affiliateTag: 'smartbuy_fk', commissionRate: 0.03 },
  croma: { slug: 'croma', name: 'Croma', affiliateTag: 'smartbuy_cr', commissionRate: 0.025 },
};

export const MOCK_RIDE_PROVIDERS = [
  { slug: 'uber', name: 'Uber', deepLink: 'https://m.uber.com/looking', liveAvailable: false },
  { slug: 'ola', name: 'Ola', deepLink: 'https://book.olacabs.com', liveAvailable: false },
  { slug: 'rapido', name: 'Rapido', deepLink: 'https://rapido.bike', liveAvailable: false },
];
