#!/usr/bin/env -S node
import type { Contract as End } from '../../snapshots/5606a0d9bdcad7cde80e5cfa6ff7c379eb39b406f44e745ce1bd5c61d08e8f61/contract';
import endContract from '../../snapshots/5606a0d9bdcad7cde80e5cfa6ff7c379eb39b406f44e745ce1bd5c61d08e8f61/contract.json' with { type: 'json' };
import {
  Migration,
  MigrationCLI,
  checkExpression,
  col,
  fn,
  lit,
  primaryKey,
} from '@prisma/orm-postgres/migration';

export default class M extends Migration<never, End> {
  override readonly endContractJson = endContract;

  override get operations() {
    return [
      this.createSchema({ schema: 'public' }),
      this.createTable({
        schema: 'public',
        table: 'adminAuditLog',
        columns: [
          col('action', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('adminUserId', 'uuid', { codecRef: { codecId: 'pg/uuid@1' } }),
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('id', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('ipAddress', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('metadata', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('targetId', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('targetType', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('userAgent', 'text', { codecRef: { codecId: 'pg/text@1' } }),
        ],
        constraints: [
          primaryKey(['id']),
          checkExpression(
            'adminAuditLog_action_check_1f5f7664',
            "\"action\" IN ('ADMIN_LOGIN_SUCCESS', 'ADMIN_LOGIN_FAILED', 'ADMIN_LOGOUT', 'ADMIN_SESSION_REVOKED', 'ADMIN_PASSWORD_CHANGED', 'RECOVERY_TOKEN_ISSUED', 'RECOVERY_TOKEN_USED', 'RECOVERY_REQUEST_DENIED', 'PROVIDER_UPDATED', 'MERCHANT_UPDATED', 'AFFILIATE_RULE_UPDATED', 'PRODUCT_MERGED', 'PRODUCT_UNMERGED', 'SETTINGS_UPDATED', 'USER_LOCKED', 'USER_UNLOCKED')",
          ),
        ],
      }),
      this.createTable({
        schema: 'public',
        table: 'adminLoginAttempt',
        columns: [
          col('attemptedAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('email', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('id', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('ipAddress', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('success', 'bool', {
            notNull: true,
            default: lit(false),
            codecRef: { codecId: 'pg/bool@1' },
          }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'adminSession',
        columns: [
          col('adminUserId', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('expiresAt', 'timestamptz', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('id', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('ipAddress', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('revokedAt', 'timestamptz', { codecRef: { codecId: 'pg/timestamptz-string@1' } }),
          col('tokenHash', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('userAgent', 'text', { codecRef: { codecId: 'pg/text@1' } }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'adminUser',
        columns: [
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('displayName', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('email', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('failedLoginAttempts', 'int4', {
            notNull: true,
            default: lit(0),
            codecRef: { codecId: 'pg/int4@1' },
          }),
          col('id', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('lastFailedLoginAt', 'timestamptz', {
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('lastLoginAt', 'timestamptz', { codecRef: { codecId: 'pg/timestamptz-string@1' } }),
          col('lockReason', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('lockedAt', 'timestamptz', { codecRef: { codecId: 'pg/timestamptz-string@1' } }),
          col('mfaEnabled', 'bool', {
            notNull: true,
            default: lit(false),
            codecRef: { codecId: 'pg/bool@1' },
          }),
          col('mfaSecretEnc', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('passwordHash', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('recoveryTokenExpiresAt', 'timestamptz', {
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('recoveryTokenHash', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('role', 'text', {
            notNull: true,
            default: lit('ADMIN'),
            codecRef: { codecId: 'pg/text@1' },
          }),
          col('updatedAt', 'timestamptz', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
        ],
        constraints: [
          primaryKey(['id']),
          checkExpression('adminUser_role_check_f0aaa5a4', "\"role\" IN ('ADMIN', 'SUPER_ADMIN')"),
        ],
      }),
      this.createTable({
        schema: 'public',
        table: 'affiliateClick',
        columns: [
          col('affiliateProgram', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('affiliateUrlId', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('clickId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('destinationUrl', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('deviceInfo', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('id', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('ipAddress', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('listingId', 'uuid', { codecRef: { codecId: 'pg/uuid@1' } }),
          col('merchantId', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('productId', 'uuid', { codecRef: { codecId: 'pg/uuid@1' } }),
          col('searchId', 'uuid', { codecRef: { codecId: 'pg/uuid@1' } }),
          col('sessionId', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('userId', 'uuid', { codecRef: { codecId: 'pg/uuid@1' } }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'affiliateCommission',
        columns: [
          col('commissionRate', 'numeric', { codecRef: { codecId: 'pg/numeric@1' } }),
          col('confirmedAmount', 'numeric', { codecRef: { codecId: 'pg/numeric@1' } }),
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('currency', 'text', {
            notNull: true,
            default: lit('INR'),
            codecRef: { codecId: 'pg/text@1' },
          }),
          col('estimatedAmount', 'numeric', { codecRef: { codecId: 'pg/numeric@1' } }),
          col('id', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('merchantId', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('notes', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('orderId', 'uuid', { codecRef: { codecId: 'pg/uuid@1' } }),
          col('paidAmount', 'numeric', { codecRef: { codecId: 'pg/numeric@1' } }),
          col('state', 'text', {
            notNull: true,
            default: lit('CLICKED'),
            codecRef: { codecId: 'pg/text@1' },
          }),
          col('stateChangedAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('updatedAt', 'timestamptz', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
        ],
        constraints: [
          primaryKey(['id']),
          checkExpression(
            'affiliateCommission_state_check_9c9e5dc4',
            "\"state\" IN ('CLICKED', 'PENDING', 'CONFIRMED', 'REJECTED', 'CANCELLED', 'PAID')",
          ),
        ],
      }),
      this.createTable({
        schema: 'public',
        table: 'affiliateOrder',
        columns: [
          col('clickId', 'uuid', { codecRef: { codecId: 'pg/uuid@1' } }),
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('currency', 'text', {
            notNull: true,
            default: lit('INR'),
            codecRef: { codecId: 'pg/text@1' },
          }),
          col('externalOrderId', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('id', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('merchantId', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('orderAmount', 'numeric', { codecRef: { codecId: 'pg/numeric@1' } }),
          col('orderDate', 'timestamptz', { codecRef: { codecId: 'pg/timestamptz-string@1' } }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'affiliateProgram',
        columns: [
          col('cookieDurationDays', 'int4', { codecRef: { codecId: 'pg/int4@1' } }),
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('id', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('name', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('network', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('paymentTerms', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('status', 'text', {
            notNull: true,
            default: lit('PENDING'),
            codecRef: { codecId: 'pg/text@1' },
          }),
          col('trackingParam', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('updatedAt', 'timestamptz', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
        ],
        constraints: [
          primaryKey(['id']),
          checkExpression(
            'affiliateProgram_status_check_b33e4718',
            "\"status\" IN ('ACTIVE', 'PENDING', 'INACTIVE')",
          ),
        ],
      }),
      this.createTable({
        schema: 'public',
        table: 'commissionRule',
        columns: [
          col('category', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('effectiveFrom', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('effectiveTo', 'timestamptz', { codecRef: { codecId: 'pg/timestamptz-string@1' } }),
          col('exclusions', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('existingCustomerRate', 'numeric', { codecRef: { codecId: 'pg/numeric@1' } }),
          col('id', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('merchantId', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('newCustomerRate', 'numeric', { codecRef: { codecId: 'pg/numeric@1' } }),
          col('productId', 'uuid', { codecRef: { codecId: 'pg/uuid@1' } }),
          col('ratePercent', 'numeric', { notNull: true, codecRef: { codecId: 'pg/numeric@1' } }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'customerScreenshot',
        columns: [
          col('confirmed', 'bool', {
            notNull: true,
            default: lit(false),
            codecRef: { codecId: 'pg/bool@1' },
          }),
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('extractedData', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('fileName', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('id', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('mimeType', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('sessionId', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('storageKey', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('userId', 'uuid', { codecRef: { codecId: 'pg/uuid@1' } }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'customerSubmittedFare',
        columns: [
          col('confirmed', 'bool', {
            notNull: true,
            default: lit(false),
            codecRef: { codecId: 'pg/bool@1' },
          }),
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('currency', 'text', {
            notNull: true,
            default: lit('INR'),
            codecRef: { codecId: 'pg/text@1' },
          }),
          col('etaMinutes', 'int4', { codecRef: { codecId: 'pg/int4@1' } }),
          col('fare', 'numeric', { notNull: true, codecRef: { codecId: 'pg/numeric@1' } }),
          col('id', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('providerSlug', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('sessionId', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('tripDetails', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('userId', 'uuid', { codecRef: { codecId: 'pg/uuid@1' } }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'merchant',
        columns: [
          col('affiliateId', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('affiliateProgramId', 'uuid', { codecRef: { codecId: 'pg/uuid@1' } }),
          col('configJson', 'text', {
            notNull: true,
            default: lit('{}'),
            codecRef: { codecId: 'pg/text@1' },
          }),
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('deepLinkTemplate', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('defaultCommissionRate', 'numeric', { codecRef: { codecId: 'pg/numeric@1' } }),
          col('id', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('name', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('providerId', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('slug', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('status', 'text', {
            notNull: true,
            default: lit('ACTIVE'),
            codecRef: { codecId: 'pg/text@1' },
          }),
          col('updatedAt', 'timestamptz', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
        ],
        constraints: [
          primaryKey(['id']),
          checkExpression(
            'merchant_status_check_474ffc3d',
            "\"status\" IN ('ACTIVE', 'INACTIVE', 'PENDING_APPROVAL', 'NOT_SUPPORTED')",
          ),
        ],
      }),
      this.createTable({
        schema: 'public',
        table: 'merchantListing',
        columns: [
          col('affiliateUrl', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('availability', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('canonicalProductId', 'uuid', { codecRef: { codecId: 'pg/uuid@1' } }),
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('currency', 'text', {
            notNull: true,
            default: lit('INR'),
            codecRef: { codecId: 'pg/text@1' },
          }),
          col('dataFreshness', 'text', {
            notNull: true,
            default: lit('LIVE'),
            codecRef: { codecId: 'pg/text@1' },
          }),
          col('deliveryInfo', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('id', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('matchConfidence', 'numeric', { codecRef: { codecId: 'pg/numeric@1' } }),
          col('merchantId', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('merchantProductId', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('mrp', 'numeric', { codecRef: { codecId: 'pg/numeric@1' } }),
          col('price', 'numeric', { codecRef: { codecId: 'pg/numeric@1' } }),
          col('providerId', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('rating', 'numeric', { codecRef: { codecId: 'pg/numeric@1' } }),
          col('returnPolicy', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('reviewCount', 'int4', { codecRef: { codecId: 'pg/int4@1' } }),
          col('seller', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('sellerRating', 'numeric', { codecRef: { codecId: 'pg/numeric@1' } }),
          col('sourceTimestamp', 'timestamptz', {
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('title', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('updatedAt', 'timestamptz', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('url', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('warranty', 'text', { codecRef: { codecId: 'pg/text@1' } }),
        ],
        constraints: [
          primaryKey(['id']),
          checkExpression(
            'merchantListing_dataFreshness_check_17b3be66',
            "\"dataFreshness\" IN ('LIVE', 'CACHED', 'HISTORICAL', 'CUSTOMER_PROVIDED', 'ESTIMATED', 'UNAVAILABLE')",
          ),
        ],
      }),
      this.createTable({
        schema: 'public',
        table: 'notificationPreference',
        columns: [
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('email', 'bool', {
            notNull: true,
            default: lit(true),
            codecRef: { codecId: 'pg/bool@1' },
          }),
          col('id', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('inApp', 'bool', {
            notNull: true,
            default: lit(true),
            codecRef: { codecId: 'pg/bool@1' },
          }),
          col('push', 'bool', {
            notNull: true,
            default: lit(false),
            codecRef: { codecId: 'pg/bool@1' },
          }),
          col('updatedAt', 'timestamptz', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('userId', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'priceAlert',
        columns: [
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('currency', 'text', {
            notNull: true,
            default: lit('INR'),
            codecRef: { codecId: 'pg/text@1' },
          }),
          col('id', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('merchantId', 'uuid', { codecRef: { codecId: 'pg/uuid@1' } }),
          col('notificationChannel', 'text', {
            notNull: true,
            default: lit('EMAIL'),
            codecRef: { codecId: 'pg/text@1' },
          }),
          col('productId', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('status', 'text', {
            notNull: true,
            default: lit('ACTIVE'),
            codecRef: { codecId: 'pg/text@1' },
          }),
          col('targetPrice', 'numeric', { notNull: true, codecRef: { codecId: 'pg/numeric@1' } }),
          col('triggeredAt', 'timestamptz', { codecRef: { codecId: 'pg/timestamptz-string@1' } }),
          col('userId', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
        ],
        constraints: [
          primaryKey(['id']),
          checkExpression(
            'priceAlert_notificationChannel_check_1a8380c5',
            "\"notificationChannel\" IN ('EMAIL', 'PUSH', 'IN_APP')",
          ),
          checkExpression(
            'priceAlert_status_check_c944e73b',
            "\"status\" IN ('ACTIVE', 'TRIGGERED', 'CANCELLED', 'EXPIRED')",
          ),
        ],
      }),
      this.createTable({
        schema: 'public',
        table: 'priceObservation',
        columns: [
          col('availability', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('currency', 'text', {
            notNull: true,
            default: lit('INR'),
            codecRef: { codecId: 'pg/text@1' },
          }),
          col('id', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('listingId', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('merchantId', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('mrp', 'numeric', { codecRef: { codecId: 'pg/numeric@1' } }),
          col('observedAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('price', 'numeric', { notNull: true, codecRef: { codecId: 'pg/numeric@1' } }),
          col('productId', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('source', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'product',
        columns: [
          col('brand', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('canonicalAttributes', 'text', {
            notNull: true,
            default: lit('{}'),
            codecRef: { codecId: 'pg/text@1' },
          }),
          col('category', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('description', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('id', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('identifiers', 'text', {
            notNull: true,
            default: lit('{}'),
            codecRef: { codecId: 'pg/text@1' },
          }),
          col('images', 'text', {
            notNull: true,
            default: lit('[]'),
            codecRef: { codecId: 'pg/text@1' },
          }),
          col('model', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('specifications', 'text', {
            notNull: true,
            default: lit('{}'),
            codecRef: { codecId: 'pg/text@1' },
          }),
          col('subcategory', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('title', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('updatedAt', 'timestamptz', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'productIdentifier',
        columns: [
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('id', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('productId', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('type', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('value', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'productVariant',
        columns: [
          col('attributes', 'text', {
            notNull: true,
            default: lit('{}'),
            codecRef: { codecId: 'pg/text@1' },
          }),
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('id', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('name', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('productId', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('sku', 'text', { codecRef: { codecId: 'pg/text@1' } }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'provider',
        columns: [
          col('affiliateAvailable', 'bool', {
            notNull: true,
            default: lit(false),
            codecRef: { codecId: 'pg/bool@1' },
          }),
          col('allowedDomains', 'text', {
            notNull: true,
            default: lit('[]'),
            codecRef: { codecId: 'pg/text@1' },
          }),
          col('apiAvailable', 'bool', {
            notNull: true,
            default: lit(false),
            codecRef: { codecId: 'pg/bool@1' },
          }),
          col('baseUrl', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('category', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('commissionNotes', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('configJson', 'text', {
            notNull: true,
            default: lit('{}'),
            codecRef: { codecId: 'pg/text@1' },
          }),
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('dataMode', 'text', {
            notNull: true,
            default: lit('MOCK'),
            codecRef: { codecId: 'pg/text@1' },
          }),
          col('errorCount', 'int4', {
            notNull: true,
            default: lit(0),
            codecRef: { codecId: 'pg/int4@1' },
          }),
          col('id', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('lastSuccessfulSync', 'timestamptz', {
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('name', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('rateLimitPerMin', 'int4', { codecRef: { codecId: 'pg/int4@1' } }),
          col('slug', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('status', 'text', {
            notNull: true,
            default: lit('PENDING_APPROVAL'),
            codecRef: { codecId: 'pg/text@1' },
          }),
          col('supportedOperations', 'text', {
            notNull: true,
            default: lit('[]'),
            codecRef: { codecId: 'pg/text@1' },
          }),
          col('termsNotes', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('updatedAt', 'timestamptz', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
        ],
        constraints: [
          primaryKey(['id']),
          checkExpression(
            'provider_category_check_5e7dad6e',
            "\"category\" IN ('ECOMMERCE', 'TRAVEL_FLIGHT', 'TRAVEL_HOTEL', 'TRAVEL_BUS', 'TRAVEL_TRAIN', 'CAR_RENTAL', 'RIDE_SERVICE', 'OTHER')",
          ),
          checkExpression(
            'provider_dataMode_check_9e7c106a',
            "\"dataMode\" IN ('OFFICIAL_API', 'AFFILIATE_API', 'PRODUCT_FEED', 'AUTHORIZED_PARTNER', 'PERMITTED_PUBLIC', 'LICENSED_THIRD_PARTY', 'CUSTOMER_PROVIDED', 'MANUAL_CHECK', 'MOCK')",
          ),
          checkExpression(
            'provider_status_check_474ffc3d',
            "\"status\" IN ('ACTIVE', 'INACTIVE', 'PENDING_APPROVAL', 'NOT_SUPPORTED')",
          ),
        ],
      }),
      this.createTable({
        schema: 'public',
        table: 'providerCredential',
        columns: [
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('credentialType', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('encryptedValue', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('expiresAt', 'timestamptz', { codecRef: { codecId: 'pg/timestamptz-string@1' } }),
          col('id', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('providerId', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('updatedAt', 'timestamptz', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'providerSyncJob',
        columns: [
          col('completedAt', 'timestamptz', { codecRef: { codecId: 'pg/timestamptz-string@1' } }),
          col('errorMessage', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('id', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('metadata', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('providerId', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('startedAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('status', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'recommendation',
        columns: [
          col('businessScore', 'numeric', { notNull: true, codecRef: { codecId: 'pg/numeric@1' } }),
          col('combinedScore', 'numeric', { notNull: true, codecRef: { codecId: 'pg/numeric@1' } }),
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('customerScore', 'numeric', { notNull: true, codecRef: { codecId: 'pg/numeric@1' } }),
          col('explanation', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('id', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('productId', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('savingsAmount', 'numeric', { codecRef: { codecId: 'pg/numeric@1' } }),
          col('savingsPercent', 'numeric', { codecRef: { codecId: 'pg/numeric@1' } }),
          col('searchId', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('type', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'savedProduct',
        columns: [
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('id', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('productId', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('userId', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'savedSearch',
        columns: [
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('id', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('intent', 'text', {
            notNull: true,
            default: lit('{}'),
            codecRef: { codecId: 'pg/text@1' },
          }),
          col('query', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('userId', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'search',
        columns: [
          col('category', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('completedAt', 'timestamptz', { codecRef: { codecId: 'pg/timestamptz-string@1' } }),
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('id', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('parsedIntent', 'text', {
            notNull: true,
            default: lit('{}'),
            codecRef: { codecId: 'pg/text@1' },
          }),
          col('query', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('resultCount', 'int4', {
            notNull: true,
            default: lit(0),
            codecRef: { codecId: 'pg/int4@1' },
          }),
          col('sessionId', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('status', 'text', {
            notNull: true,
            default: lit('PENDING'),
            codecRef: { codecId: 'pg/text@1' },
          }),
          col('userId', 'uuid', { codecRef: { codecId: 'pg/uuid@1' } }),
        ],
        constraints: [
          primaryKey(['id']),
          checkExpression(
            'search_status_check_cd6c4c40',
            "\"status\" IN ('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'PARTIAL')",
          ),
        ],
      }),
      this.createTable({
        schema: 'public',
        table: 'searchResult',
        columns: [
          col('badge', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('businessScore', 'numeric', { codecRef: { codecId: 'pg/numeric@1' } }),
          col('combinedScore', 'numeric', { codecRef: { codecId: 'pg/numeric@1' } }),
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('customerScore', 'numeric', { codecRef: { codecId: 'pg/numeric@1' } }),
          col('explanation', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('id', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('listingId', 'uuid', { codecRef: { codecId: 'pg/uuid@1' } }),
          col('productId', 'uuid', { codecRef: { codecId: 'pg/uuid@1' } }),
          col('rank', 'int4', { notNull: true, codecRef: { codecId: 'pg/int4@1' } }),
          col('searchId', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'systemSetting',
        columns: [
          col('key', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('updatedAt', 'timestamptz', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('value', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
        ],
        constraints: [primaryKey(['key'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'user',
        columns: [
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('email', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('id', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('lockReason', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('lockedAt', 'timestamptz', { codecRef: { codecId: 'pg/timestamptz-string@1' } }),
          col('name', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('passwordHash', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('phone', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('updatedAt', 'timestamptz', {
            notNull: true,
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.createTable({
        schema: 'public',
        table: 'userSession',
        columns: [
          col('createdAt', 'timestamptz', {
            notNull: true,
            default: fn('now()'),
            codecRef: { codecId: 'pg/timestamptz-string@1' },
          }),
          col('deviceLabel', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('expiresAt', 'timestamptz', { codecRef: { codecId: 'pg/timestamptz-string@1' } }),
          col('id', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
          col('ipAddress', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('lastActiveAt', 'timestamptz', { codecRef: { codecId: 'pg/timestamptz-string@1' } }),
          col('revokedAt', 'timestamptz', { codecRef: { codecId: 'pg/timestamptz-string@1' } }),
          col('sessionTokenHash', 'text', { notNull: true, codecRef: { codecId: 'pg/text@1' } }),
          col('userAgent', 'text', { codecRef: { codecId: 'pg/text@1' } }),
          col('userId', 'uuid', { notNull: true, codecRef: { codecId: 'pg/uuid@1' } }),
        ],
        constraints: [primaryKey(['id'])],
      }),
      this.addUnique({
        schema: 'public',
        table: 'adminSession',
        constraint: 'adminSession_tokenHash_key',
        columns: ['tokenHash'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'adminUser',
        constraint: 'adminUser_email_key',
        columns: ['email'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'affiliateClick',
        constraint: 'affiliateClick_clickId_key',
        columns: ['clickId'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'merchant',
        constraint: 'merchant_slug_key',
        columns: ['slug'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'merchantListing',
        constraint: 'merchantListing_merchantId_merchantProductId_key',
        columns: ['merchantId', 'merchantProductId'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'notificationPreference',
        constraint: 'notificationPreference_userId_key',
        columns: ['userId'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'productIdentifier',
        constraint: 'productIdentifier_type_value_key',
        columns: ['type', 'value'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'provider',
        constraint: 'provider_slug_key',
        columns: ['slug'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'savedProduct',
        constraint: 'savedProduct_userId_productId_key',
        columns: ['userId', 'productId'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'user',
        constraint: 'user_email_key',
        columns: ['email'],
      }),
      this.addUnique({
        schema: 'public',
        table: 'userSession',
        constraint: 'userSession_sessionTokenHash_key',
        columns: ['sessionTokenHash'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'adminAuditLog',
        index: 'adminAuditLog_action_idx_cd0d2116',
        columns: ['action'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'adminAuditLog',
        index: 'adminAuditLog_adminUserId_idx_0ce093a3',
        columns: ['adminUserId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'adminAuditLog',
        index: 'adminAuditLog_createdAt_idx_9575dbd7',
        columns: ['createdAt'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'adminLoginAttempt',
        index: 'adminLoginAttempt_email_attemptedAt_idx_1515496b',
        columns: ['email', 'attemptedAt'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'adminSession',
        index: 'adminSession_adminUserId_idx_0ce093a3',
        columns: ['adminUserId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'affiliateClick',
        index: 'affiliateClick_createdAt_idx_9575dbd7',
        columns: ['createdAt'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'affiliateClick',
        index: 'affiliateClick_listingId_idx_953decda',
        columns: ['listingId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'affiliateClick',
        index: 'affiliateClick_merchantId_idx_ee13c67b',
        columns: ['merchantId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'affiliateClick',
        index: 'affiliateClick_searchId_idx_fa57cfdf',
        columns: ['searchId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'affiliateClick',
        index: 'affiliateClick_userId_idx_a489d58a',
        columns: ['userId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'affiliateCommission',
        index: 'affiliateCommission_merchantId_idx_ee13c67b',
        columns: ['merchantId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'affiliateCommission',
        index: 'affiliateCommission_orderId_idx_d284871b',
        columns: ['orderId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'affiliateCommission',
        index: 'affiliateCommission_state_idx_ea3378ea',
        columns: ['state'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'affiliateOrder',
        index: 'affiliateOrder_clickId_idx_a6668424',
        columns: ['clickId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'affiliateOrder',
        index: 'affiliateOrder_merchantId_idx_ee13c67b',
        columns: ['merchantId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'commissionRule',
        index: 'commissionRule_category_idx_f2600f8e',
        columns: ['category'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'commissionRule',
        index: 'commissionRule_merchantId_idx_ee13c67b',
        columns: ['merchantId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'customerScreenshot',
        index: 'customerScreenshot_sessionId_idx_29f415d4',
        columns: ['sessionId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'customerScreenshot',
        index: 'customerScreenshot_userId_idx_a489d58a',
        columns: ['userId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'customerSubmittedFare',
        index: 'customerSubmittedFare_sessionId_idx_29f415d4',
        columns: ['sessionId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'customerSubmittedFare',
        index: 'customerSubmittedFare_userId_idx_a489d58a',
        columns: ['userId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'merchant',
        index: 'merchant_affiliateProgramId_idx_5118a731',
        columns: ['affiliateProgramId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'merchant',
        index: 'merchant_providerId_idx_d1904c54',
        columns: ['providerId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'merchantListing',
        index: 'merchantListing_canonicalProductId_idx_397e2257',
        columns: ['canonicalProductId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'merchantListing',
        index: 'merchantListing_merchantId_idx_ee13c67b',
        columns: ['merchantId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'merchantListing',
        index: 'merchantListing_providerId_idx_d1904c54',
        columns: ['providerId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'priceAlert',
        index: 'priceAlert_productId_idx_5858600a',
        columns: ['productId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'priceAlert',
        index: 'priceAlert_status_idx_e98638ab',
        columns: ['status'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'priceAlert',
        index: 'priceAlert_userId_idx_a489d58a',
        columns: ['userId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'priceObservation',
        index: 'priceObservation_listingId_idx_953decda',
        columns: ['listingId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'priceObservation',
        index: 'priceObservation_merchantId_idx_ee13c67b',
        columns: ['merchantId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'priceObservation',
        index: 'priceObservation_productId_idx_5858600a',
        columns: ['productId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'priceObservation',
        index: 'priceObservation_productId_observedAt_idx_975dccd5',
        columns: ['productId', 'observedAt'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'product',
        index: 'product_brand_idx_13825d71',
        columns: ['brand'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'product',
        index: 'product_category_idx_f2600f8e',
        columns: ['category'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'productIdentifier',
        index: 'productIdentifier_productId_idx_5858600a',
        columns: ['productId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'productVariant',
        index: 'productVariant_productId_idx_5858600a',
        columns: ['productId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'provider',
        index: 'provider_category_idx_f2600f8e',
        columns: ['category'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'provider',
        index: 'provider_status_idx_e98638ab',
        columns: ['status'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'providerCredential',
        index: 'providerCredential_providerId_idx_d1904c54',
        columns: ['providerId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'providerSyncJob',
        index: 'providerSyncJob_providerId_idx_d1904c54',
        columns: ['providerId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'recommendation',
        index: 'recommendation_productId_idx_5858600a',
        columns: ['productId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'recommendation',
        index: 'recommendation_searchId_idx_fa57cfdf',
        columns: ['searchId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'savedProduct',
        index: 'savedProduct_productId_idx_5858600a',
        columns: ['productId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'savedProduct',
        index: 'savedProduct_userId_idx_a489d58a',
        columns: ['userId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'savedSearch',
        index: 'savedSearch_userId_idx_a489d58a',
        columns: ['userId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'search',
        index: 'search_createdAt_idx_9575dbd7',
        columns: ['createdAt'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'search',
        index: 'search_sessionId_idx_29f415d4',
        columns: ['sessionId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'search',
        index: 'search_userId_idx_a489d58a',
        columns: ['userId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'searchResult',
        index: 'searchResult_listingId_idx_953decda',
        columns: ['listingId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'searchResult',
        index: 'searchResult_productId_idx_5858600a',
        columns: ['productId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'searchResult',
        index: 'searchResult_searchId_idx_fa57cfdf',
        columns: ['searchId'],
      }),
      this.createIndex({
        schema: 'public',
        table: 'userSession',
        index: 'userSession_userId_idx_a489d58a',
        columns: ['userId'],
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'adminAuditLog',
        foreignKey: {
          name: 'adminAuditLog_adminUserId_fkey',
          columns: ['adminUserId'],
          references: { schema: 'public', table: 'adminUser', columns: ['id'] },
          onDelete: 'setNull',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'adminSession',
        foreignKey: {
          name: 'adminSession_adminUserId_fkey',
          columns: ['adminUserId'],
          references: { schema: 'public', table: 'adminUser', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'affiliateClick',
        foreignKey: {
          name: 'affiliateClick_userId_fkey',
          columns: ['userId'],
          references: { schema: 'public', table: 'user', columns: ['id'] },
          onDelete: 'setNull',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'affiliateClick',
        foreignKey: {
          name: 'affiliateClick_searchId_fkey',
          columns: ['searchId'],
          references: { schema: 'public', table: 'search', columns: ['id'] },
          onDelete: 'setNull',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'affiliateClick',
        foreignKey: {
          name: 'affiliateClick_merchantId_fkey',
          columns: ['merchantId'],
          references: { schema: 'public', table: 'merchant', columns: ['id'] },
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'affiliateClick',
        foreignKey: {
          name: 'affiliateClick_listingId_fkey',
          columns: ['listingId'],
          references: { schema: 'public', table: 'merchantListing', columns: ['id'] },
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'affiliateCommission',
        foreignKey: {
          name: 'affiliateCommission_orderId_fkey',
          columns: ['orderId'],
          references: { schema: 'public', table: 'affiliateOrder', columns: ['id'] },
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'affiliateOrder',
        foreignKey: {
          name: 'affiliateOrder_clickId_fkey',
          columns: ['clickId'],
          references: { schema: 'public', table: 'affiliateClick', columns: ['id'] },
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'affiliateOrder',
        foreignKey: {
          name: 'affiliateOrder_merchantId_fkey',
          columns: ['merchantId'],
          references: { schema: 'public', table: 'merchant', columns: ['id'] },
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'commissionRule',
        foreignKey: {
          name: 'commissionRule_merchantId_fkey',
          columns: ['merchantId'],
          references: { schema: 'public', table: 'merchant', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'customerScreenshot',
        foreignKey: {
          name: 'customerScreenshot_userId_fkey',
          columns: ['userId'],
          references: { schema: 'public', table: 'user', columns: ['id'] },
          onDelete: 'setNull',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'customerSubmittedFare',
        foreignKey: {
          name: 'customerSubmittedFare_userId_fkey',
          columns: ['userId'],
          references: { schema: 'public', table: 'user', columns: ['id'] },
          onDelete: 'setNull',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'merchant',
        foreignKey: {
          name: 'merchant_providerId_fkey',
          columns: ['providerId'],
          references: { schema: 'public', table: 'provider', columns: ['id'] },
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'merchant',
        foreignKey: {
          name: 'merchant_affiliateProgramId_fkey',
          columns: ['affiliateProgramId'],
          references: { schema: 'public', table: 'affiliateProgram', columns: ['id'] },
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'merchantListing',
        foreignKey: {
          name: 'merchantListing_canonicalProductId_fkey',
          columns: ['canonicalProductId'],
          references: { schema: 'public', table: 'product', columns: ['id'] },
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'merchantListing',
        foreignKey: {
          name: 'merchantListing_merchantId_fkey',
          columns: ['merchantId'],
          references: { schema: 'public', table: 'merchant', columns: ['id'] },
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'merchantListing',
        foreignKey: {
          name: 'merchantListing_providerId_fkey',
          columns: ['providerId'],
          references: { schema: 'public', table: 'provider', columns: ['id'] },
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'notificationPreference',
        foreignKey: {
          name: 'notificationPreference_userId_fkey',
          columns: ['userId'],
          references: { schema: 'public', table: 'user', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'priceAlert',
        foreignKey: {
          name: 'priceAlert_userId_fkey',
          columns: ['userId'],
          references: { schema: 'public', table: 'user', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'priceAlert',
        foreignKey: {
          name: 'priceAlert_productId_fkey',
          columns: ['productId'],
          references: { schema: 'public', table: 'product', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'priceObservation',
        foreignKey: {
          name: 'priceObservation_productId_fkey',
          columns: ['productId'],
          references: { schema: 'public', table: 'product', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'priceObservation',
        foreignKey: {
          name: 'priceObservation_merchantId_fkey',
          columns: ['merchantId'],
          references: { schema: 'public', table: 'merchant', columns: ['id'] },
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'priceObservation',
        foreignKey: {
          name: 'priceObservation_listingId_fkey',
          columns: ['listingId'],
          references: { schema: 'public', table: 'merchantListing', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'productIdentifier',
        foreignKey: {
          name: 'productIdentifier_productId_fkey',
          columns: ['productId'],
          references: { schema: 'public', table: 'product', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'productVariant',
        foreignKey: {
          name: 'productVariant_productId_fkey',
          columns: ['productId'],
          references: { schema: 'public', table: 'product', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'providerCredential',
        foreignKey: {
          name: 'providerCredential_providerId_fkey',
          columns: ['providerId'],
          references: { schema: 'public', table: 'provider', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'providerSyncJob',
        foreignKey: {
          name: 'providerSyncJob_providerId_fkey',
          columns: ['providerId'],
          references: { schema: 'public', table: 'provider', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'recommendation',
        foreignKey: {
          name: 'recommendation_searchId_fkey',
          columns: ['searchId'],
          references: { schema: 'public', table: 'search', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'recommendation',
        foreignKey: {
          name: 'recommendation_productId_fkey',
          columns: ['productId'],
          references: { schema: 'public', table: 'product', columns: ['id'] },
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'savedProduct',
        foreignKey: {
          name: 'savedProduct_userId_fkey',
          columns: ['userId'],
          references: { schema: 'public', table: 'user', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'savedProduct',
        foreignKey: {
          name: 'savedProduct_productId_fkey',
          columns: ['productId'],
          references: { schema: 'public', table: 'product', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'savedSearch',
        foreignKey: {
          name: 'savedSearch_userId_fkey',
          columns: ['userId'],
          references: { schema: 'public', table: 'user', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'search',
        foreignKey: {
          name: 'search_userId_fkey',
          columns: ['userId'],
          references: { schema: 'public', table: 'user', columns: ['id'] },
          onDelete: 'setNull',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'searchResult',
        foreignKey: {
          name: 'searchResult_searchId_fkey',
          columns: ['searchId'],
          references: { schema: 'public', table: 'search', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'searchResult',
        foreignKey: {
          name: 'searchResult_productId_fkey',
          columns: ['productId'],
          references: { schema: 'public', table: 'product', columns: ['id'] },
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'searchResult',
        foreignKey: {
          name: 'searchResult_listingId_fkey',
          columns: ['listingId'],
          references: { schema: 'public', table: 'merchantListing', columns: ['id'] },
        },
      }),
      this.addForeignKey({
        schema: 'public',
        table: 'userSession',
        foreignKey: {
          name: 'userSession_userId_fkey',
          columns: ['userId'],
          references: { schema: 'public', table: 'user', columns: ['id'] },
          onDelete: 'cascade',
        },
      }),
    ];
  }
}

MigrationCLI.run(import.meta.url, M);
